### ISSUE TITLE
Check EDOT SDKS' feature table

### ISSUE THREAD

**Issue by hegerchr** [elastic/opentelemetry#118]
The [table showing the feature support on each EDOT SDK](https://github.com/elastic/opentelemetry/blob/main/docs/_edot-sdks/index.md) is drafted. Please check the table, add the missing information and validate that no feature is missing in the table.

The table is generated from the data provided in the [features.yml](https://github.com/elastic/opentelemetry/blob/main/docs/_edot-sdks/features.yml) file.

Checklist

- [x] EDOT .NET
- [x] EDOT Java (https://github.com/elastic/opentelemetry/pull/135)
- [x] EDOT Node.js (https://github.com/elastic/opentelemetry/pull/121)
- [x] EDOT PHP (https://github.com/elastic/opentelemetry/pull/138)
- [x] EDOT Python (https://github.com/elastic/opentelemetry/pull/123)
- [x] EDOT Android (https://github.com/elastic/opentelemetry/pull/140)
- [x] EDOT iOS

**Comment by hegerchr** [comment]
@elastic/apm-agent-devs, @bryce-b could you please have a look?

**Comment by trentm** [comment]
@AlexanderWert A Q on the `log-*` features in the table:

```yaml
  - name: Logs Collection
    link: https://opentelemetry.io/docs/specs/otel/logs/#log-correlation
...
  - name: Logs Correlation
    link: https://opentelemetry.io/docs/specs/otel/logs/#opentelemetry-solution
```

Q1: Are those URLs backwards? The `#log-correlation` link should be on the second item right? If so, I can make a PR.
