### ISSUE TITLE
[Documentation] Build custom collector

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/opentelemetry#5]
Similar to https://opentelemetry.io/docs/collector/custom-collector/, but specific to the elastic-agent dependendencies

1. install ocb
2. use custom `builder-config.yaml`
<details>
<summary>builder-config.yaml</summary>

```
dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.107.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.106.1
  - gomod: go.opentelemetry.io/collector/extension/memorylimiterextension v0.106.1

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.106.1
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.106.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.106.1
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.106.1

processors:
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.106.1
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.106.1

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.106.1
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.106.1

connectors:
  - gomod: 	github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.106.1
```

</details>

Note: list of components can be found - https://github.com/elastic/elastic-agent/blob/main/internal/pkg/otel/README.md (except - elasticinframetricsprocessor)

3. ./ocb --config builder-config.yaml
4. use binary `otelcol-dev/otelcol-dev`

cc @mlunadia
