### ISSUE TITLE
How to Setup nodeAffinity for the open-telemetry/opentelemetry-kube-stack replicaset (collectors)?

### ISSUE THREAD

**Issue by mgrossFreudenberg** [elastic/opentelemetry#70]
We use the helm opentelemetry-kube-stack open-telemetry/opentelemetry-kube-stack to monitor our K8S.

I tried to override nodeaffinity in the helm configuration however it is not picked up by the replicaset monitoring the cluster.

Part of the helm configuration changed:

```yaml
...
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: agentpool
              operator: NotIn
              values:
                - wpool
....
```

**Comment by rogercoll** [comment]
@mgrossFreudenberg Could you share which version of the `open-telemetry/opentelemetry-kube-stack` Helm Chart is being used? Is the shared configuration defined at the root level of the YAML file?

The `affinity` configuration can be globally applied to any Pod deployed by the Helm Chart if it is defined under the [defaultCRConfig](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-kube-stack/values.yaml#L216):

```yaml
...
defaultCRConfig:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: agentpool
                operator: In
                values:
                  - wpool
...
```

The config can also be applied to a specific collector type (e.g the `cluster` collector which gathers the K8s metrics/events):

```yaml
...
collectors:
  #  Cluster is a K8s deployment EDOT collector focused on gathering telemetry
  #  at the cluster level (Kubernetes Events and cluster metrics).
  cluster:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - wpool
...
```
